version: '3'
services:
  python-server:
    build: .
    image: python-server:pythonServer
    command: python src/run.py
    ports:
    - "5000:5000"
    volumes:
    - .:/src
    links:
    - redis
    - db:database
  redis:
    image: redis
  db:
    image: mongo:latest 