version: '3'
services:
  python-server:
    build: .
    image: python-server:pythonServer
    command: flask run
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - ./src:/src
    links:
    - db:database
  db:
    image: mongo:latest 